language: go

go:
  - "1.12"
  - master

matrix:
  allow_failures:
    - go: master
  fast_finish: true

# services:
#   -docker

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install automake libtool make gcc
  - tar -zxf yara-3.10.0.tar.gz
  - cd yara-3.10.0
  - ./bootstrap.sh
  - ./configure
  - make
  - sudo make install

install:
  - env GO111MODULE=on make deps

script:
  - env GO111MODULE=on make linux
  - env GO111MODULE=on go test .
