language: go

go:
  - "1.12"
  - master

matrix:
  allow_failures:
    - go: master
  fast_finish: true

# services:
#   -docker

install:
  - env GO111MODULE=on make deps

script:
  - env GO111MODULE=on make linux
  - env GO111MODULE=on go test .
